version: "3"

services:
  backend:
      container_name: nodejs
      build: .
      ports:
        - "3333:3333"
      volumes:
        - .:/usr/app
      links:
        - mongo
  mongo:
      container_name: mongo
      image: mongo:latest
      ports:
        - "27017:27017"
      volumes:
        - ./data:/data/db